### ISSUE TITLE
gir1.2-gtop-2.0 seems to be required in ubuntu gnome 17.04

### ISSUE THREAD

**Issue by tos-kamiya** [tpenguin/gnome-stats-pro#1]
Hi,

I notice that GnomeStatsPro installation fails in Ubuntu Gnome 17.04 amd64.
After installing gir1.2-gtop-2.0, I could successfully install GnomeStatsPro and it works fine!

Thank you.

**Comment by tpenguin** [comment]
Thank you for the report!

I have added a note to the readme.
