### ISSUE TITLE
GnomeStatsPro doesn't notice when a network interface disappears

### ISSUE THREAD

**Issue by garymoon** [tpenguin/gnome-stats-pro#11]
When a network interface is removed (in this case, tun0 for OpenVPN), GnomeStatsPro doesn't notice, and syslog fills will the below on each refresh:

```
Jul 05 22:11:52 gary-precision org.gnome.Shell.desktop[3187]: glibtop(c=3187): [WARNING] Failed to open "/sys/class/net/tun0/statistics/rx_packets": No such file or directory
Jul 05 22:11:52 gary-precision org.gnome.Shell.desktop[3187]: glibtop(c=3187): [WARNING] Failed to open "/sys/class/net/tun0/statistics/tx_packets": No such file or directory
Jul 05 22:11:52 gary-precision org.gnome.Shell.desktop[3187]: glibtop(c=3187): [WARNING] Failed to open "/sys/class/net/tun0/statistics/rx_bytes": No such file or directory
Jul 05 22:11:52 gary-precision org.gnome.Shell.desktop[3187]: glibtop(c=3187): [WARNING] Failed to open "/sys/class/net/tun0/statistics/tx_bytes": No such file or directory
Jul 05 22:11:52 gary-precision org.gnome.Shell.desktop[3187]: glibtop(c=3187): [WARNING] Failed to open "/sys/class/net/tun0/statistics/rx_errors": No such file or directory
Jul 05 22:11:52 gary-precision org.gnome.Shell.desktop[3187]: glibtop(c=3187): [WARNING] Failed to open "/sys/class/net/tun0/statistics/tx_errors": No such file or directory
Jul 05 22:11:52 gary-precision org.gnome.Shell.desktop[3187]: glibtop(c=3187): [WARNING] Failed to open "/sys/class/net/tun0/statistics/collisions": No such file or directory
```

**Comment by jbenden** [comment]
Is the tun0 device shutdown or completely removed from the system?

**Comment by jbenden** [comment]
I made changes at 6c2fbdb which will hopefully resolve problems; please let me know how testing goes! Thanks!

**Comment by jbenden** [comment]
I've added additional commits after local testing, so please try out the latest within the `master` branch... Thanks!

**Comment by garymoon** [comment]
This seems to work perfectly in testing, thank you @jbenden! Initially I was struggling, but it seems I neglected to restart gnome after pulling from the repo :1st_place_medal: 

If you're not already using it, the "extensions" extension can be useful for things like this https://extensions.gnome.org/extension/1036/extensions/.

I can also confirm the fixes for the theming stuff are still working perfectly <3
