### ISSUE TITLE
Height is higher than the topbar in gnome 3.32

### ISSUE THREAD

**Issue by Williangalvani** [tpenguin/gnome-stats-pro#16]
Apparently they shrinked the topbar, and the height here is staticly set to 28px.
![Screenshot from 2019-03-16 15-23-41](https://user-images.githubusercontent.com/4013804/54479794-98f5f800-47ff-11e9-98aa-a8d061486cfd.png)

**Comment by jbenden** [comment]
Fixed in #17 . Thanks!
