### ISSUE TITLE
No longer tracks network speed in GNOME 3.32

### ISSUE THREAD

**Issue by sardaukar** [tpenguin/gnome-stats-pro#19]
Using the extension in 3.32, network speed is always 0. Manjaro Linux, latest updates.

**Comment by jbenden** [comment]
Do you have ['libnm-glib`](https://www.archlinux.org/packages/extra/x86_64/libnm-glib/) installed?

**Comment by jbenden** [comment]
Also requires [`libgtop`](https://www.archlinux.org/packages/extra/x86_64/libgtop/) to be installed, for reading netspeed data.

**Comment by sardaukar** [comment]
I have both installed.

**Comment by sardaukar** [comment]
I can see maximums but not the current speed. The maximum over 2 hours is ~47Kb/s now.

**Comment by jbenden** [comment]
May I have a region capture (image) of the broken part, so I can understand further the situation?

**Comment by sardaukar** [comment]
![Untitled](https://user-images.githubusercontent.com/153407/56092115-a8746980-5eaf-11e9-8c96-82708bde1950.png)

Hope it helps. The maximum is always really low and goes down as time goes by.

**Comment by jbenden** [comment]
Thank you for your time on this! I have found the problem and resolved it. Please use this Git repository version, instead of the GNOME Extensions page. I will submit an update to them in a while, after seeing if more 3.32 problems exist...

Thanks again!
-Joe

**Comment by sardaukar** [comment]
There seems to be something wrong with the code. I'm using the git version, and when I enable the extension, `gnome-shell`s CPU usage goes up to 66%. When I disable the extension, goes back to ~2%.
