### ISSUE TITLE
GnomeStatsPro doesn't survive resume from suspend or unlocking the screen

### ISSUE THREAD

**Issue by elpraga** [tpenguin/gnome-stats-pro#2]
I have decided to open a proper bug report. 

The issue might be with the locking mechanism instead. Resuming from suspend could be only a side effect. 

I don't know how to get additional information or a log to help you, I can see no additional information besides the triangle and grayed out entry in Gnome Tweak Tool. 

Please, let me know how can I help.

Tomas

**Comment by tpenguin** [comment]
I believe I may have solved this problem with the latest changes made.

Would it be possible for you to test the latest source code (master branch or v1.0.2 tag)? If you are unable to easily do so, I was planning on submitting the latest release to GNOME's site - but they may not approve of the changes for a bit.

Thank you for your time and patience!
-Joe

**Comment by elpraga** [comment]
Great!
The fix works! I just downloaded the 1.0.2 tag and copied it directly over the extensions files on my SSD. 
It would be great to push it to the official site, as I noticed I wasn't the only one experiencing this issue.

Thanks!
