### ISSUE TITLE
Release a Gnome 3.32 compatible version

### ISSUE THREAD

**Issue by gjm** [tpenguin/gnome-stats-pro#21]
If I install the extension from the Gnome extensions site, the available version doesn't work with Gnome 3.32. I have to install from git to have a working compatible version.

**Comment by bamartin125** [comment]
I have the same issue. What does it take to make this release?

**Comment by jbenden** [comment]
Hi,

I have created a release (v1.2.5) and uploaded it to GNOME extensions (version 10 on this site). It should appear once they review the files.

Best regards,
-Joe
