### ISSUE TITLE
Error: Expected type object for Argument 'cancellable'

### ISSUE THREAD

**Issue by alberpilot** [tpenguin/gnome-stats-pro#22]
Hello!

I'm getting the following error: 
```
Mar 23 12:42:23 dellwazuh gnome-shell[2484]: JS ERROR: Error: Expected type object for Argument 'cancellable' but got type 'number'#012_update_iface_list@/home/alberpilot/.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:1095:17#012wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
```
Could you please help? This is my version:

```
  "url": "http://ThrallingPenguin.com/products/gnome-stats-pro", 
  "uuid": "gnome-stats-pro@thrallingpenguin.com", 
  "version": 10
```

Thanks

**Comment by jbenden** [comment]
Thank you for your report!

I am in need of some extra information:

- What version of GNOME are you running?
- What Linux distribution and version are you running?

Thanks!
-Joe

**Comment by alberpilot** [comment]
OS version

```
 ~ cat /etc/os-release                            
NAME="Pop!_OS"
VERSION="19.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 19.10"
VERSION_ID="19.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=eoan
UBUNTU_CODENAME=eoan
LOGO=distributor-logo-pop-os
```
Gnome version:
```
 ~ sudo gnome-shell --version
[sudo] password for alberpilot: 
GNOME Shell 3.34.3
```

Thanks a lot

**Comment by jbenden** [comment]
Hello,

I have created a test environment and have the extension running with minor problems (that I am looking into).

Have you installed the requirements? Namely, the package `gir1.2-gtop-2.0` is required.

After installing that package, restarting GNOME Shell (or log out and in), and using Tweak Tool; I have the extension running.

FYI: The minor issue is that the network graph is not functioning.

Best regards,
-Joe

**Comment by jbenden** [comment]
I have pushed new commits to the master branch which resolve the minor issues found with GNOME Shell 3.34.

If you could easily test these, would you mind? :)

If not, no problem! I can release a new version that will trickle downwards via GNOME Extensions web site.

Best regards,
-Joe

**Comment by jbenden** [comment]
I have submitted the extension to GNOME extension project, and it is currently under review. Hopefully it will be promoted shortly.

Please reopen this bug report if the new version does not solve the problems that were experienced.

Thanks for your bug report!
-Joe

**Comment by alberpilot** [comment]
Hello @jbenden 

 Sorry for the late response, I hadn't time for trying it. I updated the extension and I will test it. 
Thanks a lof for your great work here, really appreciated!

Regards, 
Alberto R
