### ISSUE TITLE
Not working on gnome-shell 3.38 (deb testing)

### ISSUE THREAD

**Issue by moddie666** [tpenguin/gnome-stats-pro#25]
`gnome-shell[3232]: JS ERROR: Extension gnome-stats-pro@thrallingpenguin.com: Error: No property x_fill on StBin#012_init@/home/BLÄH/.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:396:22#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012_parent@resource:///org/gnome/gjs/modules/script/_legacy.js:39:21#012_init@/home/BLÄH/.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:663:14#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012_Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10#012newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21#012_createIndicators@/home/BLÄH/.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:1235:31#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012_init@/home/BLÄH/.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:1223:16#012wrapper@resource:///org/gnome/gjs/modules/script/_legacy.js:82:27#012_Base.prototype._construct@resource:///org/gnome/gjs/modules/script/_legacy.js:18:10#012newClass@resource:///org/gnome/gjs/modules/script/_legacy.js:114:21#012init@/home/BLÄH/.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:1321:12#012_callExtensionInit@resource:///org/gnome/shell/ui/extensionSystem.js:428:50#012loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:345:27#012_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:586:18#012collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28#012_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:565:19#012_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:595:18#012_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:626:18#012init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14#012_initializeUI@resource:///org/gnome/shell/ui/main.js:269:22#012start@resource:///org/gnome/shell/ui/main.js:159:5#012@<main>:1:47`

simply commenting out all the occurences of `x_fill: true` and `y_fill: true` seems to fix the issue
```
egrep -nr "(x|y)_fill" .local/share/gnome-shell/extensions/gnome-stats-pro\@thrallingpenguin.com/
.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:75://            x_fill: true,
.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:76://            y_fill: true
.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:129://            x_fill: true,
.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:130://            y_fill: true
.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com/extension.js:398://                                  x_fill: true, y_fill: true
```

**Comment by jbenden** [comment]
Hello, would you mind trying the current master branch? It has changes that should solve this bug report.

Thanks,
-Joe
