### ISSUE TITLE
No JS module 'tweener' found in search path

### ISSUE THREAD

**Issue by romanovzky** [tpenguin/gnome-stats-pro#28]
Hi there,
After the Gnome 3.38 update on Manjaro (Arch) the extensions stopped working, showing the error
```
No JS module 'tweener' found in search path
```
A quick google shows that [it seems that tweener import has changed path](https://askubuntu.com/questions/1286212/no-js-module-tweener-found-in-search-path-gnome-shell-extension-error-on-ubun).

Cheers,
M

**Comment by jbenden** [comment]
Hello, would you mind trying the current master branch? It has changes that should solve this bug report.

Thanks,
-Joe

**Comment by romanovzky** [comment]
Hi again. I tried installing via github but I'm obviously missing something. What I did
- Removed the old version through the gnome extensions website
- Cloned the repo to `.local/share/gnome-shell/extensions`, which produced the folder `gnome-stats-pro` with the contents of the repo.
However, it doesn't show on the Extensions app.

**Comment by jbenden** [comment]
Hi,

The folder name must match the extension's fully-qualified name. So please run this and then restart Gnome:

```
cd ~/.local/share/gnome-shell/extensions
mv gnome-stats-pro "gnome-stats-pro@thrallingpenguin.com"
```

Thank you for trying!
-Joe

**Comment by romanovzky** [comment]
Yes, that worked! Thanks!
Any plans on pushing it to the extensions website?

**Comment by jbenden** [comment]
Hello,

After testing this solution more, it completely breaks on older Gnome Shell. So, it's not fixed just yet.

Does anyone know how to make the `x_expand` & `y_expand` on `St.Bin` work properly across the older Gnome Shell and newer one? I found most extensions removing it entirely and others pushing the `St.Bin` attributes onto the child control; however, I couldn't get the later one to work.

Any help would be appreciated!
-Joe

**Comment by jbenden** [comment]
Commits may have resolved this issue.
