### ISSUE TITLE
Broken on Gnome 45

### ISSUE THREAD

**Issue by caleb173** [tpenguin/gnome-stats-pro#32]
The package gnome-stats-pro gives the error "Requiring GTop, version none: Typelib file for namespace 'GTop' (any version) not found" after an upgrade from gnome 44. The screenshot of both the error and my device is attached below
![Screenshot from 2024-01-16 09-09-43](https://github.com/tpenguin/gnome-stats-pro/assets/62430711/729a8e2d-2e7b-42f9-bc96-628a313f6118)
![Screenshot from 2024-01-16 09-06-50](https://github.com/tpenguin/gnome-stats-pro/assets/62430711/6fdb6105-6f44-474c-b039-7cb4a7d8548c)

**Comment by jbenden** [comment]
Can you confirm that the libgtop packages are installed?

**Comment by caleb173** [comment]
Yes, They seem to be installed

**Comment by jbenden** [comment]
Does this help fix the problem? https://ubuntuhandbook.org/index.php/2023/11/cpu-memory-load-graph-gnome-panel/

**Comment by caleb173** [comment]
> Does this help fix the problem? https://ubuntuhandbook.org/index.php/2023/11/cpu-memory-load-graph-gnome-panel/

Thanks so much, it does.

**Comment by caleb173** [comment]
Yes, it does.
