### ISSUE TITLE
GnomeStatsPro doesn't appear on https://extensions.gnome.org/ search

### ISSUE THREAD

**Issue by JuniorPolegato** [tpenguin/gnome-stats-pro#34]
Hi!

GnomeStatsPro does not appear in the https://extensions.gnome.org/ search, we need to change from current version to all versions filter.

So, please, the latest version of GnomeStatsPro needs to be published.

**Comment by jbenden** [comment]
Hi! I have submitted a new version. Thanks for the bug report!
