### ISSUE TITLE
all lines are blue - pilot error?

### ISSUE THREAD

**Issue by sudoer** [tpenguin/gnome-stats-pro#4]
I hope I am doing something wrong... I just installed GnomeStatsPro on Ubuntu 17.10 (gnome-shell 3.26.1-0ubuntu4), and it looks like just what I need.

I was surprised that all of the bars on the chart are the same blue color.  Changes to the stylesheet.css file do not have any effect.  I hope I am just doing something stupid.

Do you know why my bars are not using the colors from the CSS file?

![gnome-stats-pro-blue](https://user-images.githubusercontent.com/1240842/32685405-60512d0e-c65e-11e7-8a07-815b4c868f51.png)

**Comment by jbenden** [comment]
Hello,

I've installed the development area to Ubuntu 17.10 will success and it is functioning. So off to a good start! I haven't tried the extension on the latest Gnome Shell.

I am not sure I follow you with the CSS. Which CSS file are you attempting to change? If it is the included one, it will only pick up the changes after restarting Gnome Shell (Alt+F2 and enter `r` + ENTER) or after a reboot.

If you are attempting to edit a custom CSS somewhere, then please do share how and where and I'll be happy to research this bug you are experiencing.

Best Regards,
-Joe

**Comment by tpenguin** [comment]
A new version of the extension just posted:

https://extensions.gnome.org/review/7870
