### ISSUE TITLE
Can I get the extension working on MATE?

### ISSUE THREAD

**Issue by jayekaye** [tpenguin/gnome-stats-pro#5]
I loved it on gnome 3.26. Hoping I can get it running on MATE now. If this is not the right place for this, please direct me tot he proper area and I apologoze.. Thx!

**Comment by tpenguin** [comment]
I do not believe that MATE uses a GNOME Shell compatible DE component and therefore will not execute JavaScript desktop extensions. If you can find supporting documentation for executing JavaScript desktop extensions, then it may be possible.

**Comment by jayekaye** [comment]
Darn-it, finding that out is slightly above my expertise ATM but I pick
things up VERY quickly, any direction would be appreciated! Thx
