### ISSUE TITLE
Lots of errors in logs

### ISSUE THREAD

**Issue by gjm** [tpenguin/gnome-stats-pro#6]
I get keep getting these errors in my logs:

> ...
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-cpu-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-grid-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-mem-used-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-grid-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-swap-used-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-grid-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-network-in-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-network-out-color' 
> Jan  2 22:35:41 falcon gnome-shell[1623]: Did not find color property '-grid-color' 
> ...

and they keep repeating.

**Comment by jbenden** [comment]
Hello,
What is the version of GnomeStatsPro, your operating system, and the GNOME Shell?

I am running successfully with Ubuntu 16.04, GNOME 3.18, and the latest GnomeStatsPro.

Best Regards,
-Joe

**Comment by gjm** [comment]
Hi thanks for the reply.

I'm running Ubuntu 17.10, GNOME 3.26 and the latest GnomeStatsPro.

**Comment by jbenden** [comment]
Would it be possible for you to test the master branch, before I publish a new version? I am confident that I have resolved these logging messages, and improved display on small monitors (due to VM testing.)

Best Regards,
-Joe

**Comment by gjm** [comment]
How can i do that? Is there some sort of documentation on how to do that?


Gonçalo Marrafa

**Comment by jbenden** [comment]
I have uploaded a new version to GNOME; hopefully they will approve of the extension soon so you may update it following their instructions.

https://extensions.gnome.org/extension/1043/gnomestatspro/

Best Regards,
-Joe

**Comment by gjm** [comment]
Thanks!

Will give feedback as soon as i upgrade.



Gonçalo Marrafa

**Comment by gjm** [comment]
Hello again.

I've manually installed version 1.2.0 and the problem is still there. My
syslog is full of:

...
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'mem-used-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'grid-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'swap-used-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'grid-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'network-in-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'network-out-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'grid-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'mem-used-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'grid-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'swap-used-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'grid-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'network-in-color'
Jan 17 14:33:04 falcon gnome-shell[1731]: Did not find color property
'network-out-color'
...




Gonçalo Marrafa

**Comment by jbenden** [comment]
Hello,

Were all of the following steps all performed?

- Ensure the latest `stylesheet.css` is present alongside `extension.js`
- Restart the extension, GNOME, or reboot

If these steps have been completed, then please provide more information. I successfully tested with Ubuntu 16.04 and 17.10; with normal operation and between the lock and desktop screens.

If possible, please try to find the steps needed for me to reproduce these log messages.

Best Regards,
-Joe

**Comment by gjm** [comment]
I'm attaching the requested files of my installed version. I renamed
extension.js to extension because of Gmail doesn't allow me to send .js
files.

After restarting the extension the errors don't appear immediately, only
after a while. I can't exactly pinpoint if they start showing as a
consequence of some action of mine of they just do after a while.

If there is something else i can do to help debug the issue please tell me.
​​​​

​​​​
Gonçalo Marrafa

**Comment by jbenden** [comment]
The file did not attach, but I may not need it.

Please try the following, but only if they apply to your use cases. Additionally, I need for you to check for these log messages after attempting each and every one.

- Allow your screensaver to start, then go back into the desktop and look for log messages.
- Allow your screen to lock, then go back into the desktop and look for log messages.
- If applicable, allow your machine to hibernate, then check the log

PS: In me asking for these, you may realize there are other possible situations. If so, please check for them too. ;)

**Comment by gjm** [comment]
Hello again.

I tried your suggestions and i can consistently reproduce the issue with
these steps:

1. Restart gnome shell (alt-f2 + r)
2. Lock screen (super + l)

After unlock the messages start appearing.

Thanks again!



Gonçalo Marrafa

**Comment by jbenden** [comment]
Would you mind trying this?

Please download `extension.js` and `stylesheet.css` from GitHub master branch. Place these files (most likely) in to `~/.local/share/gnome-shell/extensions/gnome-stats-pro@thrallingpenguin.com`. Next, restart the Gnome Shell using alt-f2 + r. Finally, see if you can reproduce the problems still.

Thanks,
-Joe

**Comment by gjm** [comment]
Hi. Extension doesn't start:

Jan 27 16:27:33 falcon gnome-shell[24644]: Extension "
gnome-stats-pro@thrallingpenguin.com" had error: SyntaxError: redeclaration
of let layout

Thanks.



Gonçalo Marrafa

**Comment by jbenden** [comment]
Sorry about that. My editor managed to copy and paste a block of code twice. For some reason, older Ubuntu 16.04 runs it without reporting an error.

If you wouldn't mind, please try to install the files again to see if it fixes it.

**Comment by gjm** [comment]
Sorry the problem still exists...

Thanks again for your time on this issue.


Gonçalo Marrafa

**Comment by jbenden** [comment]
I'm at a loss. I cannot reproduce any log message output from the extension now. I've been testing with Ubuntu 17.10 and 16.04. If you have any ideas on how I could possibly reproduce it with different logging settings or another OS version, please let me know,

Sorry!

**Comment by gjm** [comment]
Can't figure that out either... Thanks for your time.


Gonçalo Marrafa

**Comment by tpenguin** [comment]
The latest version finally posted active:

https://extensions.gnome.org/review/7870

**Comment by garymoon** [comment]
I'm experiencing this on 18.04. It does appear to be influenced by sleep/lid closure (there aren't errors on a fresh boot). Is there anything I can do to help test further?

**Comment by jbenden** [comment]
Does the graph state (all the graph data) restore properly, if you force a sleep/lid closure no longer than 5 minutes? I am wondering if it "loses it's brains" during restore.

**Comment by garymoon** [comment]
The graph data does seem to be preserved following a brief sleep.

**Comment by jbenden** [comment]
When you put your machine to sleep and wake it, does it only log a small set of these errors and stop? Or does it keep logging them from that point forward? (I know they'll log again if the machine goes to sleep...)

I am thinking their is a window of time where the ticks to update occur, but gnome-shell hasn't yet reloaded the stylesheet; because the system is still restoring from disk. To handle this situation, I've found a different way to get the stylesheet colors which should not log messages; but, I want to fully understand the problem before simply switching it.

Thanks for your patience and time!
-Joe

**Comment by garymoon** [comment]
No sir, thank  _you_ for an extension so valuable that I'm willing to tolerate my messy syslog :)

Anecdotally it seems to last forever if it starts. My machine has been awake for several hours now, and it's still printing the errors.

**Comment by jbenden** [comment]
I've committed 1e7546b which will hopefully help you out. Please let me know how testing goes. Thanks!

**Comment by garymoon** [comment]
Suspended and resumed several times, and not a hint of anything wrong! :D Thanks so much Joseph, you're a legend!

While testing I was on- and offline with my VPN, and noticed issue #11. I opened a ticket, but it's relatively very low impact (more an FYI). Please feel free to ignore/close if you're not interested in fixing :+1:

**Comment by jbenden** [comment]
Thank you for your help debugging this problem! Since it seems fixed, I'm closing this bug report. Please reopen or create a new one if needed, in the future!

-Joe
