### ISSUE TITLE
Add support for scaling

### ISSUE THREAD

**Issue by auipga** [tpenguin/gnome-stats-pro#7]
With an 4k display and scaling to 200% the indicator is too small.

I don't know whether this solution could also work for you: https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/71#issuecomment-296811289

**Comment by jbenden** [comment]
Hello,

Please try out the attached patch to see if it suits your needs with regards to Hi-DPI scaling.

I am unable to completely test, but when I hard-code scaling factors in the code; it all seems OK.

-Joe

[hi-dpi.patch.txt](https://github.com/tpenguin/gnome-stats-pro/files/1795058/hi-dpi.patch.txt)

**Comment by auipga** [comment]
Thanks for the fast reply! The toolbar elements are now perfect!
As you can see in the images, the tooltips are too high.

![cpu](https://preview.ibb.co/etW2hx/Screenshot_from_2018_03_19_21_21_42.png)
![ram](https://preview.ibb.co/kog2hx/Screenshot_from_2018_03_19_21_22_08.png)
![swap](https://preview.ibb.co/gabraH/Screenshot_from_2018_03_19_21_22_27.png)
![net](https://preview.ibb.co/hW7a2x/Screenshot_from_2018_03_19_21_22_43.png)

After taking a screenshot the tooltip did not disappear. It needs a separate mouseout on the specific chart in the top bar.
(I did like the smaller, unscaled version of the tooltip charts, but thats my personal opinion.)

**Comment by jbenden** [comment]
In `master`, I have committed only the changes relating to sizing the indicator (but not the drop-downs). The next time I release the extension, these changes will be included. Until then, you might consider installing the latest `master` branch, which includes *only* the change you requested. :)
