### ISSUE TITLE
Syslog spammed with Did not find color property

### ISSUE THREAD

**Issue by subutux** [tpenguin/gnome-stats-pro#8]
I'm currently suffering from what I think is a bug in your extension. 
my `journalctl -f`is currently flooded with the following messages multiple times a second:
```
mrt 27 10:10:27 fedora gnome-shell[1945]: Did not find color property 'cpu-color'
mrt 27 10:10:27 fedora gnome-shell[1945]: Did not find color property 'grid-color'
mrt 27 10:10:27 fedora gnome-shell[1945]: Did not find color property 'mem-used-color'
mrt 27 10:10:27 fedora gnome-shell[1945]: Did not find color property 'grid-color'
mrt 27 10:10:27 fedora gnome-shell[1945]: Did not find color property 'swap-used-color'
```
I suspect this comes from your plugin.

**Comment by tpenguin** [comment]
Duplicate of #6

**Comment by tpenguin** [comment]
Please try the latest extension available and/or the master branch, to see if the problem resolves itself.

If not, I have been unsuccessful in reproducing the problem. If you are able to somehow gather a list for reproducing the issue, with VirtualBox please, then I would be able to assist.

Thank you,
-Joe
